apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: olama
  annotations:
    scenarios.ai.sap.com/description: "Run a olama server on SAP AI Core"
    scenarios.ai.sap.com/name: "olama"
    executables.ai.sap.com/description: "olama service"
    executables.ai.sap.com/name: "olama"
  labels:
    scenarios.ai.sap.com/id: "olama"
    ai.sap.com/version: "0.0.1"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: infer.s
    spec: |
      predictor:
        imagePullSecrets:
        - name: summerdockersecret
        minReplicas: 1
        maxReplicas: 1
        containers:
        - name: kserve-container
          image: docker.io/summerlllll/olama:ai-core
          ports:
            - containerPort: 8080
              protocol: TCP
